apiVersion: v1
kind: Service
metadata: 
  name: temperaturas-backend
spec: 
   ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
   selector: 
     app: temperaturas-backend
   type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-backend
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: temperaturas-backend
  template: 
    metadata: 
      labels:
        app: temperaturas-backend
    spec: 
      containers: 
      - name:  temperaturas-backend
      image: miguellatorre/temperaturas-backend:latest
      ports: 
        - containerPort: 5000
      resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"     
      
  

